export const STATES = {
  FILED: "FILED",
  SUMMONS_ISSUED: "SUMMONS_ISSUED",
  SERVED: "SERVED",
  APPEARANCE_ENTERED: "APPEARANCE_ENTERED",
  DEFENCE_FILED: "DEFENCE_FILED",
  PLEADINGS_CLOSED: "PLEADINGS_CLOSED",
  PRE_TRIAL: "PRE_TRIAL",
  HEARING: "HEARING",
  JUDGMENT_DELIVERED: "JUDGMENT_DELIVERED",
  CLOSED: "CLOSED"
};

export const TRANSITIONS = {
  FILED: ["SUMMONS_ISSUED"],
  SUMMONS_ISSUED: ["SERVED"],
  SERVED: ["APPEARANCE_ENTERED"],
  APPEARANCE_ENTERED: ["DEFENCE_FILED"],
  DEFENCE_FILED: ["PLEADINGS_CLOSED"],
  PLEADINGS_CLOSED: ["PRE_TRIAL"],
  PRE_TRIAL: ["HEARING"],
  HEARING: ["JUDGMENT_DELIVERED"],
  JUDGMENT_DELIVERED: ["CLOSED"]
};